# this compose file is modified for the use of TCP/IP connections between containers
# it has been tested for compatibility with kata-containers runtime
# main changes are that we have had to rework networking
# environment variables are pulled from local `.env`

# key changes
# - [x] renamed with leading `mailcow-*`
#    - [x] check any `depends:`
# - [x] added build `context` to point to right location
# - [x] symlink so we can use the build info in `./data`
# - [x] rebuilt network
# - [x] removed aliases as we are using hostnames

# ip addresses
#  - [x] add in `resolv.conf` to all machines which ensures they resolve properly
#    - IP addresses for machine names are defined there
#  - [x] check subnet is valid
#  - [x] changed `ports` to `expose`

# disk requirements
# - [x] this file is using `named volumes`
#   - the volumes are symlinked to volumes in the `$PWD/volumes/` dir for convenience
# - [x] tested `volumes_from` this works fine

version: '2.1'
services:

    mailcow-unbound:
      container_name: mailcow-unbound
      image: mailcow/unbound:1.4
      build: ./data/Dockerfiles/unbound
      command: /usr/sbin/unbound
      environment:
        - TZ=${TZ}
      volumes:
        - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro
        # kata containers compatible resolv.conf symlinked 
        - ./etc/resolv.conf:/etc/resolv.conf
      restart: always
      networks:
        docker2:
          ipv4_address: 172.18.18.100

    mailcow-mysql:
      container_name: mailcow-mysql
      image: mariadb:10.2
      volumes:
        - mysql-vol-1:/var/lib/mysql/
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
        - ./etc/resolv.conf:/etc/resolv.conf
      environment:
        - TZ=${TZ}
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
      restart: always
      expose:
        - "13306" 
        # - "${SQL_PORT:-13306}/tcp"
      # ports:
        # - "${SQL_PORT:-127.0.0.1:13306}:3306"
      networks:
        docker2:
          ipv4_address: 172.18.18.101

    mailcow-redis:
      container_name: mailcow-redis
      image: redis:4-alpine
      volumes:
        - redis-vol-1:/data/
        - ./etc/resolv.conf:/etc/resolv.conf
      restart: always
      environment:
        - TZ=${TZ}
      networks:
        docker2:
          ipv4_address: 172.18.18.102

    mailcow-clamd:
      container_name: mailcow-clamd
      image: mailcow/clamd:1.15
      build: ./data/Dockerfiles/clamd
      restart: always
      environment:
        - TZ=${TZ}
        - SKIP_CLAMD=${SKIP_CLAMD:-n}
      volumes:
        - ./data/conf/clamav/:/etc/clamav/
        - ./etc/resolv.conf:/etc/resolv.conf
      networks:
        docker2:
          ipv4_address: 172.18.18.103

    mailcow-rspamd:
      container_name: mailcow-rspamd
      image: mailcow/rspamd:1.30
      build: ./data/Dockerfiles/rspamd
      stop_grace_period: 30s
      depends_on:
        - mailcow-nginx
      environment:
        - TZ=${TZ}
      volumes:
        - ./data/conf/rspamd/custom/:/etc/rspamd/custom
        - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d
        - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d
        - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
        - rspamd-vol-1:/var/lib/rspamd
        - ./etc/resolv.conf:/etc/resolv.conf
      expose:
        - "11445"
      restart: always
      networks:
        docker2:
          ipv4_address: 172.18.18.104

    mailcow-phpfpm:
      container_name: mailcow-phpfpm
      image: mailcow/phpfpm:1.23
      build: ./data/Dockerfiles/phpfpm
      command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
      depends_on:
        - mailcow-redis
      volumes:
        - ./data/web:/web:rw
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
        - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf
        - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
        - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
        - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini
        - ./etc/resolv.conf:/etc/resolv.conf
      environment:
        - CONNECT_METHOD=${CONNECT_METHOD}
        - DBHOST=${DBHOST}
        - DBCONN=${DBCONN}
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - HOSTNAME_REDIS=${HOSTNAME_REDIS}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - IMAP_PORT=${IMAP_PORT:-143}
        - IMAPS_PORT=${IMAPS_PORT:-993}
        - POP_PORT=${POP_PORT:-110}
        - POPS_PORT=${POPS_PORT:-995}
        - SIEVE_PORT=${SIEVE_PORT:-4190}
        - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
        - SMTPS_PORT=${SMTPS_PORT:-465}
        - SMTP_PORT=${SMTP_PORT:-25}
        - API_KEY=${API_KEY:-invalid}
        - API_ALLOW_FROM=${API_ALLOW_FROM:-invalid}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
      restart: always
      networks:
        docker2:
          ipv4_address: 172.18.18.105

    mailcow-sogo:
      container_name: mailcow-sogo
      image: mailcow/sogo:1.42
      build: ./data/Dockerfiles/sogo
      environment:
        - CONNECT_METHOD=${CONNECT_METHOD}
        - DBHOST=${DBHOST}
        - DBCONN=${DBCONN}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - HOSTNAME_REDIS=${HOSTNAME_REDIS}
        - TZ=${TZ}
        - LOG_LINES=${LOG_LINES:-9999}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      volumes:
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/web/inc/init_db.inc.php:/init_db.inc.php
        - ./data/conf/sogo/custom-sogo.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/custom-sogo.js
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./etc/resolv.conf:/etc/resolv.conf
      restart: always
      networks:
        docker2:
          ipv4_address: 172.18.18.106

    mailcow-dovecot:
      container_name: mailcow-dovecot
      image: mailcow/dovecot:1.44
      build: ./data/Dockerfiles/dovecot
      cap_add:
        - NET_BIND_SERVICE
      volumes:
        - ./data/conf/dovecot:/usr/local/etc/dovecot
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - ./data/conf/sogo/:/etc/sogo/
        - vmail-vol-1:/var/vmail
        - vmail-attachments-vol-1:/var/attachments
        - crypt-vol-1:/mail_crypt/
        - ./data/conf/rspamd/custom/:/etc/rspamd/custom
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./etc/resolv.conf:/etc/resolv.conf
      environment:
        - CONNECT_METHOD=${CONNECT_METHOD}
        - DBHOST=${DBHOST}
        - DBCONN=${DBCONN}       
        - RSCONN_SCK=${RSCONN_SCK}
        - LOG_LINES=${LOG_LINES:-9999}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - HOSTNAME_REDIS=${HOSTNAME_REDIS}
        - TZ=${TZ}
        - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-1440}
      expose:
        - "19991"
        - "143"
        - "993"
        - "110"
        - "995"
        - "4190"
        # - "${DOVEADM_PORT:-19991}"
        # - "${IMAP_PORT:-143}"
        # - "${IMAPS_PORT:-993}"
        # - "${POP_PORT:-110}"
        # - "${POPS_PORT:-995}"
        # - "${SIEVE_PORT:-4190}"
        # ports:
          #- "${DOVEADM_PORT:-127.0.0.1:19991}:12345"
          #- "${IMAP_PORT:-143}:143"
          #- "${IMAPS_PORT:-993}:993"
          #- "${POP_PORT:-110}:110"
          #- "${POPS_PORT:-995}:995"
          #- "${SIEVE_PORT:-4190}:4190"
      restart: always
      ulimits:
        nproc: 65535
        nofile:
          soft: 20000
          hard: 40000
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        docker2:
          ipv4_address: 172.18.18.107 


    mailcow-postfix:
      container_name: mailcow-postfix
      image: mailcow/postfix:1.27
      build: ./data/Dockerfiles/postfix
      volumes:
        - ./data/conf/postfix:/opt/postfix/conf
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - postfix-vol-1:/var/spool/postfix
        - crypt-vol-1:/var/lib/zeyple
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./etc/resolv.conf:/etc/resolv.conf
      environment:
        - CONNECT_METHOD=${CONNECT_METHOD}
        - DBHOST=${DBHOST}
        - DBCONN=${DBCONN}       
        - RSCONN_SCK=${RSCONN_SCK}
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - HOSTNAME_REDIS=${HOSTNAME_REDIS}
      cap_add:
        - NET_BIND_SERVICE
      expose:
        - "25"
        - "465"
        - "587"
        # - "${SMTP_PORT:-25}"
        # - "${SMTPS_PORT:-465}"
        # - "${SUBMISSION_PORT:-587}"
      # ports:
        # - "${SMTP_PORT:-25}:25"
        # - "${SMTPS_PORT:-465}:465"
        # - "${SUBMISSION_PORT:-587}:587"
      restart: always
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        docker2:
          ipv4_address: 172.18.18.108

    mailcow-memcached:
      container_name: mailcow-memcached
      image: memcached:alpine
      volumes:
        - ./etc/resolv.conf:/etc/resolv.conf
      restart: always
      networks:
        docker2:
          ipv4_address: 172.18.18.109

    mailcow-nginx:
      container_name: mailcow-nginx      
      depends_on:
        - mailcow-sogo
        - mailcow-phpfpm
        - mailcow-redis
      image: nginx:mainline-alpine
      command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active &&
        envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active &&
        envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active &&
        envsubst < /etc/nginx/conf.d/templates/sogo.template > /etc/nginx/conf.d/sogo.active &&
        envsubst < /etc/nginx/conf.d/templates/sogo_eas.template > /etc/nginx/conf.d/sogo_eas.active &&
        nginx -qt &&
        until ping phpfpm -c1 > /dev/null; do sleep 1; done &&
        until ping sogo -c1 > /dev/null; do sleep 1; done &&
        until ping redis -c1 > /dev/null; do sleep 1; done &&
        until ping rspamd -c1 > /dev/null; do sleep 1; done &&
        exec nginx -g 'daemon off;'"
      environment:
        - HTTPS_PORT=${HTTPS_PORT:-443}
        - HTTP_PORT=${HTTP_PORT:-80}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.18.18}
        - TZ=${TZ}
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/assets/ssl/:/etc/ssl/mail/:ro
        - ./data/conf/nginx/:/etc/nginx/conf.d/:rw
        - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
        - ./etc/resolv.conf:/etc/resolv.conf
      volumes_from:
        - mailcow-sogo
      expose:
        - "443"
        - "80"
        # - "${HTTPS_PORT:-443}"
        # - "${HTTP_PORT:-80}"
      # ports:
        # - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
        # - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
      restart: always
      networks:
        docker2:
          ipv4_address: 172.18.18.110

    mailcow-acme:
      container_name: mailcow-acme
      depends_on:
        - mailcow-nginx
      image: mailcow/acme:1.45
      build: ./data/Dockerfiles/acme
      environment:
        - CONNECT_METHOD=${CONNECT_METHOD}
        - DBHOST=${DBHOST}
        - DBCONN=${DBCONN}
        - LOG_LINES=${LOG_LINES:-9999}
        - ADDITIONAL_SAN=${ADDITIONAL_SAN}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
        - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
        - LE_STAGING=${LE_STAGING:-n}
        - TZ=${TZ}
      volumes:
        - ./data/web/.well-known/acme-challenge:/var/www/acme:rw
        - ./data/assets/ssl:/var/lib/acme/:rw
        - ./data/assets/ssl-example:/var/lib/ssl-example/:ro
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./etc/resolv.conf:/etc/resolv.conf
      restart: always
      networks:
        docker2:
          ipv4_address: 172.18.18.111

#    mailcow-netfilter:
#      container_name: mailcow-netfilter
#      image: mailcow/netfilter:1.19
#      build: ./data/Dockerfiles/netfilter
#      stop_grace_period: 30s
#      depends_on:
#        - mailcow-dovecot
#        - mailcow-postfix
#        - mailcow-sogo
#        - mailcow-phpfpm
#        - mailcow-redis
#      restart: always
#      # privileged: true
#      environment:
#        - TZ=${TZ}
#        - IPV4_NETWORK=${IPV4_NETWORK:-172.18.18}
#        - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
#        - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-n}
#        - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-n}
#        - HOSTNAME_REDIS=${HOSTNAME_REDIS}
#        # network_mode: "host"
#      volumes:
#        - /lib/modules:/lib/modules:ro
#        - ./etc/resolv.conf:/etc/resolv.conf
#      networks:
#        docker2:
#          ipv4_address: 172.18.18.112

    mailcow-watchdog:
      container_name: mailcow-watchdog
      image: mailcow/watchdog:1.29
      # Debug
      #command: /watchdog.sh
      build: ./data/Dockerfiles/watchdog
      oom_kill_disable: true
      volumes:
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./etc/resolv.conf:/etc/resolv.conf
      restart: always
      environment:
        - RSCONN_SCK=${RSCONN_SCK}
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - USE_WATCHDOG=${USE_WATCHDOG:-n}
        - WATCHDOG_NOTIFY_EMAIL=${WATCHDOG_NOTIFY_EMAIL}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.18.18}
        - IP_BY_DOCKER_API=${IP_BY_DOCKER_API:-0}
        - CHECK_UNBOUND=${CHECK_UNBOUND:-1}
        - SKIP_CLAMD=${SKIP_CLAMD:-n}
        - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
        - HTTPS_PORT=${HTTPS_PORT:-443}
      networks:
        docker2:
          ipv4_address: 172.18.18.113

#    mailcow-dockerapi:
  #      container_name: mailcow-dockerapi
  #    image: mailcow/dockerapi:1.22
  #    restart: always
  #    build: ./data/Dockerfiles/dockerapi
  #    oom_kill_disable: true
  #    environment:
    #      - TZ=${TZ}
    #  volumes:
      #    - /var/run/docker.sock:/var/run/docker.sock:ro
      #  - ./data/conf/rspamd/override.d/worker-controller-password.inc:/access.inc:rw
      #  - vmail-vol-1:/var/vmail:ro
      #  - ./etc/resolv.conf:/etc/resolv.conf
      #networks:
        #  docker2:
          #  ipv4_address: 172.18.18.114           

    # ipv6nat:
      # image: robbertkl/ipv6nat
      # restart: always
      # privileged: true
      #  network_mode: "host"
      # volumes:
        # - /var/run/docker.sock:/var/run/docker.sock:ro
        # - /lib/modules:/lib/modules:ro
        # - ./etc/resolv.conf:/etc/resolv.conf

# this is an external network which we have manually defined
networks:
  docker2:
    external:
      name: docker2

# these named volumes are symlinked to datasets
volumes:
  # Storage for email files
  vmail-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/vmail-vol-1'
      o: 'bind'

  # Storage for attachments
  vmail-attachments-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/vmail-attachments-vol-1'
      o: 'bind'
  mysql-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/mysql-vol-1'
      o: 'bind'
  mysql-socket-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/mysql-socket-vol-1'
      o: 'bind'
  redis-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/redis-vol-1'
      o: 'bind'
  rspamd-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/rspamd-vol-1'
      o: 'bind'
  postfix-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/postfix-vol-1'
      o: 'bind'
  crypt-vol-1:
    driver: local
    driver_opts:
      type: 'none'
      device: '${PWD}/volumes/crypt-vol-1'
      o: 'bind'
